# Generated by Django 3.2.5 on 2021-07-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20210730_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='saldo_brl',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
