# Generated by Django 3.2.5 on 2021-07-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfil_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='identidade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
