# Generated by Django 3.2.5 on 2021-07-26 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacao', models.IntegerField()),
                ('operacao', models.CharField(max_length=200)),
                ('nome_usuario', models.CharField(max_length=200)),
                ('cpf_usuario', models.CharField(max_length=200)),
                ('digito_conta_usuario', models.IntegerField()),
                ('conta_usuario', models.IntegerField()),
                ('agencia_usuario', models.IntegerField()),
                ('nome_favorecido', models.CharField(max_length=200)),
                ('cpf_favorecido', models.CharField(max_length=200)),
                ('conta_favorecido', models.IntegerField()),
                ('digito_conta_favorecido', models.IntegerField()),
                ('banco_favorecido', models.CharField(max_length=200)),
                ('banco_numero', models.CharField(max_length=200)),
                ('valor_transferido', models.DecimalField(max_digits=6, decimal_places=2)),
                ('data_transferencia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                
            ],
        ),
    ]
