# Generated by Django 3.2.5 on 2021-07-29 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conta_corrente', '0002_alter_transferencia_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='agencia_favorecido',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='nome_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
