# Generated by Django 3.2.5 on 2021-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_usuario',
            name='email_verificacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conta_usuario',
            name='foto_verificacao_identidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conta_usuario',
            name='foto_verificacao_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
