# Generated by Django 3.2.5 on 2021-07-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210726_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_usuario',
            name='foto_identidade',
            field=models.ImageField(blank=True, upload_to='foto_identidade/%d/%m/%Y'),
        ),
        migrations.AddField(
            model_name='conta_usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, upload_to='foto_usuario/%d/%m/%Y'),
        ),
    ]
