# Generated by Django 3.2.5 on 2021-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numero_operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacao', models.IntegerField()),
                ('nome_operacao', models.CharField(max_length=200)),
            ],
        ),
    ]
